#!/usr/bin/env python3
"""Generate small CSS references to the repository's self-hosted font files."""

from pathlib import Path

SPECS = [
    ("JetBrains Mono", 400, "jetbrains-mono-400.woff2"),
    ("JetBrains Mono", 500, "jetbrains-mono-500.woff2"),
    ("JetBrains Mono", 700, "jetbrains-mono-700.woff2"),
    ("Bricolage Grotesque", 700, "bricolage-grotesque-700.woff2"),
    ("Bricolage Grotesque", 800, "bricolage-grotesque-800.woff2"),
]
lines = ["/* Generated by build-fonts.py; no remote font providers. */"]
for family, weight, filename in SPECS:
    lines.append(
        f'@font-face{{font-family:"{family}";font-style:normal;font-weight:{weight};'
        f'font-display:swap;src:url("fonts/{filename}") format("woff2");}}'
    )
Path(__file__).with_name("fonts.css").write_text("\n".join(lines) + "\n")
