#!/usr/bin/env python3
"""Regenerate assets/fonts.css by base64-embedding the woff2 in assets/fonts/.

The woff2 are the latin subset of JetBrains Mono and Bricolage Grotesque, both
under the SIL Open Font License 1.1. Embedding them as data URIs means the page
loads fonts.css rather than the files directly, so they arrive at CSS parse time
with no separate request and no font-swap layout shift, under file:// and http.
Fetch the woff2 first (see FONTS.md), then run this to regenerate fonts.css.
"""

import base64
import pathlib

FONTS = pathlib.Path(__file__).resolve().parent / "fonts"
SPECS = [
    ("JetBrains Mono", 400, "jetbrains-mono-400.woff2"),
    ("JetBrains Mono", 500, "jetbrains-mono-500.woff2"),
    ("JetBrains Mono", 700, "jetbrains-mono-700.woff2"),
    ("Bricolage Grotesque", 700, "bricolage-grotesque-700.woff2"),
    ("Bricolage Grotesque", 800, "bricolage-grotesque-800.woff2"),
]

lines = [
    "/* Generated by build-fonts.py: self-hosted woff2 embedded as data URIs so",
    "   the fonts load under file:// as well as http, with no separate request",
    "   and no font-swap layout shift. Regenerate: python assets/build-fonts.py */",
    "",
]
for fam, wt, fn in SPECS:
    b64 = base64.b64encode((FONTS / fn).read_bytes()).decode()
    lines.append(
        f'@font-face{{font-family:"{fam}";font-style:normal;font-weight:{wt};'
        f'font-display:swap;src:url(data:font/woff2;base64,{b64}) format("woff2");}}'
    )
(pathlib.Path(__file__).resolve().parent / "fonts.css").write_text("\n".join(lines) + "\n")
print("wrote fonts.css")
